In [1]:
# !pip install torch==1.10.1+cu102 torchvision==0.11.2+cu102 torchaudio===0.10.1+cu102 -f https://download.pytorch.org/whl/cu102/torch_stable.html


In [2]:
import torch

# Tensors

#### Creating a Tensor

In [3]:
# Float Tensor
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
# vector / list type tensor
t2 = torch.tensor([1.,2,3])
t2
# all elems will have same dtype

tensor([1., 2., 3.])

In [5]:
# matrix tensor
t3 = torch.tensor([[1.,2],[2,3],[3,4]])
t3

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])

In [6]:
# 3-D tensor
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [7]:
# To get shape
t3.shape

torch.Size([3, 2])

# Tensor Operations and Gradients

In [8]:
# Making set of tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [9]:
# Performing operations on tensors
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

We can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. This feature of PyTorch is called autograd (automatic gradients).

In [10]:
y.backward()


In [11]:
print("dy/dx", x.grad)
print("dy/dw", w.grad)
print("dy/db", b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


### Interoperability with Numpy

In [12]:
import numpy as np

In [13]:
a = np.array([[1,2],[3.,4]])
a

array([[1., 2.],
       [3., 4.]])

##### Convert np to tensor

In [14]:
# 2 methods to convert np array to tensor
# 1 -> it creates a copy 
t1 = torch.tensor(a)
print(t1)
# 2 -> it uses the same space
t2 = torch.from_numpy(a)
print(t2)


tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [15]:
a.dtype, t1.dtype

(dtype('float64'), torch.float64)

##### Convert tensor to np

In [16]:
z = t1.numpy()
z
# We do this as sometimes we need the final result as a numpy array.

array([[1., 2.],
       [3., 4.]])

# Tensor Functions

In [17]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [18]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 1.,  2.],
        [ 2.,  3.],
        [ 3.,  4.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [19]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093],
        [ 0.9093,  0.1411],
        [ 0.1411, -0.7568],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [20]:
# Change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[ 0.8415,  0.9093],
         [ 0.9093,  0.1411]],

        [[ 0.1411, -0.7568],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])